### ISSUE TITLE
Cyrillic `н` letter bug

### ISSUE THREAD

**Issue by anuvyklack** [nvim-neorg/tree-sitter-norg#31]
Treesitter considers Cyrillic `н` letter (the analog of Latin `n`) at the beginning of the word as `NeorgMarkupVariableDelimiter` and if there is another one somewhere at the end of the word, everything between these two letters inside one paragraph becomes a variable.

For example:
```neorg
Я тоже не знал, пока в моей жизни не появились проклятые рыбки. Жизнь аквариумиста - это один сплошной стресс.
```

**Comment by mrossinek** [comment]
Thanks for the bug report! I just fixed this and hopefully we will not run into a similar issue again in the future :+1:

**Comment by anuvyklack** [comment]
Works now. Thank you!
