### ISSUE TITLE
[dev branch] Paragraph delimiters terminate parent headings instead of parent indent segments.

### ISSUE THREAD

**Issue by vhyrro** [nvim-neorg/tree-sitter-norg#37]
Reproduction example:
```
* Heading
  - \
      Text
      ---
This text no longer belongs in the heading even though it should.
```

The `---` paragraph delimiter should end the indent segment, but it instead terminates the heading.

**Comment by mrossinek** [comment]
Are you sure that this is the case? On my end this is working fine (see the test case I just pushed)

**Comment by vhyrro** [comment]
A note for all other people reading this - after a discussion on discord we managed to find a minimal reproducible example of the issue:
```
* Heading One
* Heading Two
  - \
      Text
      ---
* Heading Three
```
In this case (a heading surrounded by other headings of the same type) the `---` paragraph delimiter would incorrectly be assigned to the heading instead of the indent segment. This has now been fixed in the latest commit, so I can close this :)
