### ISSUE TITLE
MacOS | TSInstallSync norg

### ISSUE THREAD

**Issue by NachoNievaG** [nvim-neorg/tree-sitter-norg#48]
I'm trying to install the TS Parser using gcc-12 in macOS as the following:
![image](https://user-images.githubusercontent.com/83428506/226408076-e983967b-28a7-4f75-8258-e608c13b9537.png)

and i'm getting the following error:
![image](https://user-images.githubusercontent.com/83428506/226411657-280c663c-bb8a-46f5-b91a-70f6ff6e7559.png)

i tried some workarounds that i found here but i'm still not able to install the parser

i'm using the following nvim version:
```
NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local
```

if there is something else that i can bring your for context, or if i'm missing a detail, please let me know
Thank you in advanced and thank you for the hard work!

**Comment by g-battaglia-h-farm** [comment]
This worked for me:
```sh
brew install gcc@12
CC="/opt/homebrew/bin/gcc-12" nvim
CC="/opt/homebrew/bin/gcc-12" nvim -c "TSInstallSync norg"
```

**Comment by NachoNievaG** [comment]
Thank you @g-battaglia-h-farm , that actually works.
Closing
